[theme]

primaryColor = "#000000"
secondaryColor = "#ffffff"
backgroundColor="#000000" #this is the colour of dataframes etc
secondaryBackgroundColor="#006400"
textColor="#ffffff"
font="sans serif"
#current favourite green = #006400